image:
  repository: artifactory.dagility.com/docker/testvd_scm-backend
  tag: latest
  pullPolicy: Always
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx-internal
  hosts:
  - host: testvd_scm-backend-default.dagility.com
    paths:
    - /
serviceAccount:
  create: false
